# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk4041
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk4041
  template:
    metadata:
      labels:
        app: vk4041
    spec:
      containers:
      - name: book-catalog
        image: vk4041.azurecr.io/book-catalog:1
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://vk4041_zerx_user:4dzrQA95WDzdzoXyWyvZXyZfLuTuAPsP@dpg-crl9bsbtq21c73eak580-a.oregon-postgres.render.com/vk4041_zerx
      - name: inventory-management
        image: vk4041.azurecr.io/inventory-management:1
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://vk4041_zerx_user:4dzrQA95WDzdzoXyWyvZXyZfLuTuAPsP@dpg-crl9bsbtq21c73eak580-a.oregon-postgres.render.com/vk4041_zerx

---
apiVersion: v1
kind: Service
metadata:
  name: vk4041
spec:
  selector:
    app: vk4041
  ports:
    - name: book-catalog
      port: 8000
      targetPort: 8000
    - name: inventory-management
      port: 8001
      targetPort: 8001
  type: LoadBalancer
